version: '3'
services:
  db:
    image: postgres:11.4-alpine
    container_name: postgres
    ports:
    - 5432:5432
    volumes:
    - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: docker_test
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
  web:
    build: .
    container_name: django
    command: python /usr/src/django_project/manage.py runserver 0.0.0.0:8000
    volumes:
    - .:/usr/src/django_project
    ports:
    - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
    - db
volumes:
  pg_data: